package codegen

import (
	"github.com/xwb1989/sqlparser"
)

const bigcap = 500

var insns []ByteCodeOp

/*GenByteCode :
Walks along the AST generated by the sqlparser library
and generates bytecode that will be executed by the virtual
machine to carry out the sql command. The bytecode langauge
is defined in codegen/ops.go
*/
func GenByteCode(stmt sqlparser.Statement) []ByteCodeOp {
	// insns := make([]ByteCodeOp, 0, bigcap)
	// switch stmt := stmt.(type) {
	// case *sqlparser.Select:
	// 	visitSelect(*stmt)
	// case *sqlparser.Insert:
	// 	_ = stmt
	// }
	return nil
}

func visitSelect(stmt sqlparser.Select) {
	// tableExprs := stmt.From
	// table := tableExprs[0]
	// table2 := TableExprImpl{table}
	// tableName := sqlparser.GetTableName(table2)
	// insns = append(insns, GetTableOp{"dummyTableName"})
}
