package codegen

import (
	"github.com/xwb1989/sqlparser"
)

const bigcap = 500

var insns []ByteCodeOp

//Evironment that maps register names to Values
var env map[string]Value

func addOp(ByteCodeOp) Register {
}

/*GenByteCode :
Walks along the AST generated by the sqlparser library
and generates bytecode that will be executed by the virtual
machine to carry out the sql command. The bytecode langauge
is defined in codegen/ops.go
*/
func GenByteCode(stmt sqlparser.Statement) []ByteCodeOp {
	insns := make([]ByteCodeOp, 0, bigcap)
	switch stmt := stmt.(type) {
	case *sqlparser.Select:
		visitSelect(stmt)
		_ = stmt
	case *sqlparser.Insert:
		_ = stmt
	}
	return nil
}

func visitSelect(stmt sqlparser.Statement) {

}
